[gcp_service_account]
type = "service_account"
project_id = "three-466212"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCi+RONUKb/Jj35
aEJEpFmcS4XB0DXsm4J5nOMsMefYvLYHAFboXdinl4o0Rtv3ly8KZG0ggXaK6eW+
yL2VYwE6ppuQyK2Db/TgIV6EHDFvBPQhNTvM5YURS79JzQC310/uekSEkMFnt8AS
80NEsF4CTF0oSOv3n/+yXzEMXY+DrRF4U3+8EyhfgtiRIN8DNN6ytKNCc8DbHcug
a6g8nczHJlHo5od2QsewVcsu05V3903tywXsKpqC71BgAaBvYdVFlOLQ44vqt6tb
PgeFysy1NcSSJrg//jgaLoyr3cGycCDvqgIisGEdrb+qZ8zHhljk3W7ja2bJHvwl
0dR6IguRAgMBAAECggEAIW8h8LrcF7o7uqAGAFkLPUJNJY7WkTzyDor+HAH9A3zr
hxItwiwGl5NCOilTVT8B2orxzFpi/GqxxGsgYbZW+TZW8eQJnM5qGVUfM9Eo3xLQ
FsP6CbYIj5zPmI9jF1QnxM/2oI+l7eZHlFutsDjSgHw0HGChcEK1zV00Dcpf9+5E
gSJDh6ARXUqmSD9uyIpGNSIaKT/FoDcdRq3SnxDcxij74kmoxx90sww7juOoDReX
rA6pAsyo7N6SmvZJWTVq00THAVBIMnzy/P4H2Mnp6nClOLjHk82iTvlm7DEUranp
gAsGf3fHJ0BM+f+1BfMXOFPqYkl+EkbZom/17UG2MQKBgQDbkuq8aANph6Ev5D++
3jhCbF3ahtfEcgFc95A9FtemcEU89K7Z800/pwtx2PayLLCGjA7elYPoP/I7gzzy
6wn4ht7UGAp8q9soy+gRIzFS+l6438DpY1FnUe2h/XZFIkLYunBhABk8JASiTguk
9ZQY5+tN541lc/stGRUzbAmmBQKBgQC+Al/SAr8+Bvfs5kXjMjzlZtXWBDZP2LGM
YsRa0Bn4IKgJGwfigWmRW0e/d21eW5nbcClPz1YaXYCpXk2XpiUF/iSLZdNgMPWA
S5H2VNtXo/sOyyGeQmx018vRw9Mk7Kogsxxy89JUYre25eBy4moH3h3Z9XPxTgoM
czOgIxDZHQKBgGD/MtEOBcvdjXgRlZNkqWe2ZXN+s9xlHHMMLdy+tX8iA4Qc9wzy
7QIccfLWDIzDLywQvRTY6c90SDbAD/GjoOD3+4GoKSHP7V3FTfwcFtL4JVX4CklP
hYtl5trzlAaQTwVcvv4qw/sMUju8zGoPzl9+PDVK/+x8Ys4WUYZIyK5dAoGACHi+
oPRyZmeVIkDaGNkike/V1Ob3LPQyZln4+zuQDNoX4+AKp/SxKkPxnP3MKIrY/0mu
7doGssI8fFCyEPLdb7j3FCgEFqPYLlIwPdVmui+bf/takl3PzB3a/o1GmrzakP6r
ZAyu8gg8vLDfIwApThR/LDqfYsDh/dAdGyS1GZkCgYA/lSP4xFJQN699IJNGqQ+I
OWGPP7We1BpFBt7qfBRdBcf7AUKEHamE1D7irUeJun9dXcFKib/UAMrPykgl8coK
vNC+t/WikaXg04PnHWeXVd2lqqVZBY+JxcJ0cCFkB/KvSZwLbTTOoZ4do21hW1Xp
8vu+reILdqsxHyUEDQof3A==
-----END PRIVATE KEY-----"""
client_email = "divi-128@three-466212.iam.gserviceaccount.com"
client_id = "114141660243441162210"
auth_uri=  "https://accounts.google.com/o/oauth2/auth"
token_uri= "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url= "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url= "https://www.googleapis.com/robot/v1/metadata/x509/divi-128%40three-466212.iam.gserviceaccount.com"

[gemini]
api_key ="AIzaSyC9o79E9lW0eiCAxgHc8Xe0oGUPRK7dNd8"
